language: cpp
compiler:
  - gcc
  - clang
script: ./etc/travis-ci.sh
notifications:
  irc:
    - "irc.freenode.org#rerun"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq markdown
 - sudo apt-get install -qq build-essential
 - sudo apt-get install -qq devscripts
 - sudo apt-get install -qq dh-make
